log4r_config:
  pre_config:
    custom_levels:
    - DEBUG
    - PARAMS
    - INFO
    - WARN
    - ERROR
    - EXCEPTION
    - FATAL
  # define all loggers:
  loggers:
    - name          : rails
      level         : DEBUG
      trace         : 'true'
      outputters    : 
      - console
      - railsfile
 
  # define all outputters (incl. formatters)
  outputters:
  - type: StdoutOutputter
    name: console
    formatter:
      date_pattern: '%H:%M:%S'
      pattern     : '%d %l: %m'
      type        : PatternFormatter

 
  - type: FileOutputter
    name: railsfile
    filename: "log/#{ENV}.log" # notice the file extension is needed! 
    trunc: false
    formatter: 
      date_pattern: '%Y %m %d %H:%M:%S.%L %z'
      #pattern     : '[#{EC2_INSTANCE}][%p][#{APPNAME}]|[RAILS][%d][%l]: %m '
      pattern     : '[%p][%d][%l]: %m '
      type        : PatternFormatter
